### ISSUE TITLE
Warning: Bootstrapped manifest not allowed to use 'overlay' directive.

### ISSUE THREAD

**Issue by Herst** [philikon/VerticalTabs#15]
Apparently just a warning.

Source File: jar:…/extensions/%7B421e87b4-d3d2-49c8-b08f-b83f4dc88444%7D.xpi!/chrome.manifest
Line: 3

**Comment by Herst** [comment]
Oops, forgot to mention, this is with the latest Nightly, ie. Firefox 12.

**Comment by htgoebel** [comment]
I think the issue can be closed, as ther is no "overlay" directive in chrome.manifest anymore.
