### ISSUE TITLE
make scrolling possible when moving a tab

### ISSUE THREAD

**Issue by Herst** [philikon/VerticalTabs#18]
When you have more tabs than fits into the vertical space then you need to scroll but scrolling when dragging around a tab does not work.

**Comment by Luckz** [comment]
I had that problem just today :D

**Comment by Croydon** [comment]
@Luckz This is not getting maintained anymore and doesn't run anymore in up-to-date Firefox versions. You are in the wrong repository almost certainly :)

**Comment by Luckz** [comment]
Don't worry for my mental health, I also use pre-Quantum Firefox -- else I'd commit suicide or something.

(I will admit that all VTs usable in this century are darrinhenein-based. If you have a commit from somewhere else that solves exactly this, I'd happily pirate it, but as it is, moving a tab a few hundred up the list does not happen to me that often and if I really cared I could multi-select all other tabs inbetween and move those instead.)
