### ISSUE TITLE
Navigation Bar Gradient

### ISSUE THREAD

**Issue by panosl** [philikon/VerticalTabs#2]
Firefox 4b2 adds the "Tabs on Top" option for OS X, which shows up like this:

http://panos.solhost.org/temp/navigation_bar.png

a white-to-transparent gradient, which looks a bit ugly when Vertical Tabs is enabled. Easy fix is to disable the "Tabs on Top" option, which reverses the gradient, and looks as it should.

Not sure how this should be handled in code though. Should vertical tabs remove the option from the View menu or just uncheck it?

**Comment by philikon** [comment]
Good points all around. Yes, Tabs on Top should've been disabled manually. VT does this programmatically now.
