### ISSUE TITLE
Session Restore changes will probably break this Add-On

### ISSUE THREAD

**Issue by Herst** [philikon/VerticalTabs#26]
according to http://dutherenverseauborddelatable.wordpress.com/2013/05/23/add-on-breakage-continued-list-of-add-ons-that-will-probably-be-affected/

**Comment by philikon** [comment]
Thanks for the heads-up. Actually, the VerticalTabs code that uses the bits of Session Restore that slated for removal is dead (ever since groups have been removed). So the core functionality should be unaffected. The dead code should just be removed at this point.
