### ISSUE TITLE
Soon to be broken in Australis UI

### ISSUE THREAD

**Issue by noscript** [philikon/VerticalTabs#29]
If you try to use VerticalTabs on the Nightly builds, the biggest problem is the drag and drop feature. Once you start dragging a tab, all others just disappear. Not to mention that VerticalTabs's look is broken too.

There is still time before Australis lands to official Firefox release, but at least it's worth be checking already now.

**Comment by philikon** [comment]
Thanks, I'm aware of the issue.

**Comment by noscript** [comment]
Australis has arrived. Any chance to get drag and drop fixed?

**Comment by noscript** [comment]
Drag'n'drop works
